language: python
python:
  - "2.7"  # Legacy
  - "3.5"  # Debian 9 (Stretch), Ubuntu 16.04 (Xenial)
  - "3.6"  # Ubuntu 18.04 (Bionic)
  - "3.7"  # Debian 10 (Buster), Ubuntu 17.10 (Artful)
  - "3.8"  # Ubuntu 20.04 (Focal) and 20.10 (Groovy)
  - "3.9"  # Debian 11 (Bullseye)
  - "3.9-dev"  # Python alphas/betas

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.9-dev"  # Alpha and beta versions can fail

script: python tests.py
